# Generated by Django 4.1.6 on 2023-02-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clima_Tempo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_Nasc', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('cpf', models.IntegerField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=15)),
                ('situacao', models.CharField(max_length=6)),
                ('data_insc', models.DateTimeField(auto_now_add=True)),
                ('cep_principal', models.CharField(max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
