# Generated by Django 4.1.6 on 2023-02-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clima_Tempo', '0002_cliente_delete_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
